version: '3.9'

services:
  ecg-container:
    build:
      context: ./ecg-container
    container_name: ecg-container
    ports:
      - "8001:8000"
    networks:
      - internal-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8000"
      - ecg-container
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
