version: "3.9"

services:
  signal_analyzer:
    build: ./signal-analyzer
    container_name: signal-analyzer
    ports:
      - "8001:8000"
    networks:
      - bio-net

  api_gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - signal-analyzer
    networks:
      - bio-net

networks:
  bio-net:
    driver: bridge
